[[main]]
  name = "Ã€ propos"
  url = "/fr/"
  weight = 10

[[main]]
  name = "CV"
  url = "/fr/resume/"
  weight = 20

[[main]]
  name = "Blog"
  url = "/fr/blog/"
  weight = 30

[[main]]
  identifier = "github"
  name = "GitHub"
  pre = "github"
  url = "https://github.com/damione1/"
  weight = 400
  newTab = true

[[main]]
  identifier = "linkedin"
  name = "LinkedIn"
  pre = "linkedin"
  url = "https://www.linkedin.com/in/damiengoehrig/"
  weight = 400
  newTab = true
