baseURL = 'https://damione1.github.io/'
languageCode = 'en'
defaultContentLanguage = 'en'
title = 'Damien GOEHRIG'

[taxonomies]
  stack = 'stack'
  tag = 'tags'
  category = 'categories'

[module]
  [[module.imports]]
    path = 'github.com/luizdepra/hugo-coder'

[languages]
  [languages.en]
    languageName = 'English'
    title = 'Damien GOEHRIG'
    weight = 1
    contentDir = 'content/en'

    [languages.en.params]
      author = 'Damien GOEHRIG'
      description = 'Backend Software Engineer (Go)'
      keywords = 'blog,developer,personal,go,backend'
      info = ['Backend Software Engineer', 'Go & Distributed Systems']

      colorScheme = 'auto'
      hideColorSchemeToggle = false

      [[languages.en.params.social]]
        name = "GitHub"
        icon = "fa-brands fa-github"
        weight = 1
        url = "https://github.com/damione1/"

      [[languages.en.params.social]]
        name = "LinkedIn"
        icon = "fa-brands fa-linkedin"
        weight = 2
        url = "https://www.linkedin.com/in/damiengoehrig/"

    [[languages.en.menu.main]]
      name = "About"
      weight = 1
      url = "/"

    [[languages.en.menu.main]]
      name = "Projects"
      weight = 2
      url = "/projects/"

    [[languages.en.menu.main]]
      name = "Resume"
      weight = 3
      url = "/resume/"

    [[languages.en.menu.main]]
      name = "Blog"
      weight = 4
      url = "/blog/"

  [languages.fr]
    languageName = 'Français'
    title = 'Damien GOEHRIG'
    weight = 2
    contentDir = 'content/fr'

    [languages.fr.params]
      author = 'Damien GOEHRIG'
      description = 'Ingénieur logiciel backend (Go)'
      keywords = 'blog,développeur,personnel,go,backend'
      info = ['Ingénieur logiciel backend', 'Go & Systèmes distribués']

      colorScheme = 'auto'
      hideColorSchemeToggle = false

      [[languages.fr.params.social]]
        name = "GitHub"
        icon = "fa-brands fa-github"
        weight = 1
        url = "https://github.com/damione1/"

      [[languages.fr.params.social]]
        name = "LinkedIn"
        icon = "fa-brands fa-linkedin"
        weight = 2
        url = "https://www.linkedin.com/in/damiengoehrig/"

    [[languages.fr.menu.main]]
      name = "À propos"
      weight = 1
      url = "/fr/"

    [[languages.fr.menu.main]]
      name = "Projets"
      weight = 2
      url = "/fr/projects/"

    [[languages.fr.menu.main]]
      name = "CV"
      weight = 3
      url = "/fr/resume/"

    [[languages.fr.menu.main]]
      name = "Blog"
      weight = 4
      url = "/fr/blog/"
